version: '3.4'

services:
  my.wasm.dashboard:
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    container_name: my_wasm_dashboard